modLoader="javafml"
loaderVersion="[43,)"
license="GPLv3"

[[mods]]
modId="snowwaifuspell"
version="${mod_version}"
# logoFile="logo.png" #optional
displayName="Snow Waifu Spell"
authors="${mod_authors}"
description = '''
Add a Spell to make Snow Queen your Summonable Waifu!
'''